import React, { useState } from 'react';
import { Monitor, Smartphone, Settings, Code, Check } from 'lucide-react';
import { LayoutRenderer } from './LayoutRenderer';
import { DocumentDesign, Language } from '../types';

interface PreviewPanelProps {
  designData: DocumentDesign;
  markdownContent: string;
  previewMode: 'desktop' | 'mobile';
  setPreviewMode: (mode: 'desktop' | 'mobile') => void;
  lang: Language;
  t: any;
}

export const PreviewPanel: React.FC<PreviewPanelProps> = ({
  designData,
  markdownContent,
  previewMode,
  setPreviewMode,
  lang,
  t
}) => {
  const [copiedType, setCopiedType] = useState<'config' | 'html' | null>(null);

  const handleCopyLayout = () => {
    const jsonString = JSON.stringify(designData, null, 2);
    navigator.clipboard.writeText(jsonString).then(() => {
      setCopiedType('config');
      setTimeout(() => setCopiedType(null), 2000);
    });
  };

  const handleCopyHtml = async () => {
    // Get the rendered content div
    const contentElement = document.getElementById('layout-preview-content');
    if (!contentElement) return;

    // Create a complete HTML file string for "Paste as Code" or saving file
    const fullHtml = `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${designData.themeName} - Generated by LayoutForge</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body { margin: 0; }
    </style>
</head>
<body class="min-h-screen">
${contentElement.outerHTML}
</body>
</html>`;

    try {
      // Try to write rich text (HTML) and plain text (Source) to the clipboard
      const htmlBlob = new Blob([contentElement.outerHTML], { type: 'text/html' });
      const textBlob = new Blob([fullHtml], { type: 'text/plain' });
      
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/html': htmlBlob,
          'text/plain': textBlob,
        }),
      ]);
      
      setCopiedType('html');
      setTimeout(() => setCopiedType(null), 2000);
    } catch (err) {
      console.warn('Rich copy failed, falling back to text copy:', err);
      // Fallback
      navigator.clipboard.writeText(fullHtml).then(() => {
        setCopiedType('html');
        setTimeout(() => setCopiedType(null), 2000);
      });
    }
  };

  return (
    <main className="flex-1 bg-slate-200 flex flex-col min-w-[350px] relative transition-all">
      
      {/* Toolbar */}
      <div className="h-14 border-b border-slate-200/50 flex items-center justify-between px-6 bg-white/80 backdrop-blur-sm sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">{t.livePreview}</span>
        </div>
        
        <div className="flex items-center gap-2">
           {/* Device Toggle */}
           <div className="flex bg-slate-100 p-1 rounded-lg border border-slate-200 mr-2">
            <button 
              onClick={() => setPreviewMode('desktop')}
              className={`p-1.5 rounded-md transition-all ${previewMode === 'desktop' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
              title={t.desktop}
            >
              <Monitor className="w-4 h-4" />
            </button>
            <button 
              onClick={() => setPreviewMode('mobile')}
              className={`p-1.5 rounded-md transition-all ${previewMode === 'mobile' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
              title={t.mobile}
            >
              <Smartphone className="w-4 h-4" />
            </button>
          </div>

          {/* Copy Config Button */}
          <button 
            onClick={handleCopyLayout}
            className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-medium rounded-lg transition shadow-sm"
            title={t.copyConfig}
          >
            {copiedType === 'config' ? <Check className="w-3.5 h-3.5" /> : <Settings className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{copiedType === 'config' ? t.copied : 'Config'}</span>
          </button>

          {/* Copy HTML Button */}
          <button 
            onClick={handleCopyHtml}
            className="flex items-center gap-2 px-3 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-medium rounded-lg transition shadow-sm"
            title={t.copyHtml}
          >
            {copiedType === 'html' ? <Check className="w-3.5 h-3.5" /> : <Code className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{copiedType === 'html' ? t.copied : 'HTML'}</span>
          </button>
        </div>
      </div>

      {/* Canvas */}
      <div className="flex-1 overflow-y-auto relative bg-slate-200/50 flex flex-col">
         <LayoutRenderer data={designData} content={markdownContent} previewMode={previewMode} />
      </div>
    </main>
  );
};
